config:
  azure-native:location: westus3
  cst8918-a03-infra:appPath: ../
  cst8918-a03-infra:containerPort: '80'
  cst8918-a03-infra:publicPort: '80'
  cst8918-a03-infra:cpu: '1'
  cst8918-a03-infra:memory: '2'
  cst8918-a03-infra:prefixName: 'cst8918-a03-avsa0005'
  cst8918-a03-infra:imageTag: 'v0.1.0'
  cst8918a03infra:appPath: /mnt/c/Users/avsar/Masaüstü/CDO 2/DevOps-IaC/Week 3/cst8918-a03-h03-pulumi
  cst8918a03infra:prefixName: cst8918a03avsa0005
  cst8918a03infra:imageTag: v0.2.0
  cst8918a03infra:containerPort: "80"
  cst8918a03infra:publicPort: "80"
  cst8918a03infra:cpu: "1"
  cst8918a03infra:memory: "2"
