config:
  azure-native:location: westus3
  cst8918-a03-ho3-pulumi:appPath: ../
  cst8918-a03-ho3-pulumi:containerPort: '80'
  cst8918-a03-ho3-pulumi:publicPort: '80'
  cst8918-a03-ho3-pulumi:cpu: '1'
  cst8918-a03-ho3-pulumi:memory: '2'
  cst8918-a03-ho3-pulumi:prefixName: 'cst8918a03avsa0005'
  cst8918-a03-ho3-pulumi:imageTag: 'v0.2.0'